INSERT INTO reports.reporttypes(ReportTypeName, ReportTypeFilePrefix, AlternateSubject, ReportClassName) values('Отчет по минимальным ценам по возрастанию по прайсу', 'OffersReportAsc', 'Отчет по минимальным ценам по возрастанию по прайсу', 'Inforoom.ReportSystem.OffersReportAsc');

INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'ReportType','Вариант отчета','ENUM',0,1,'','1');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'ClientCode','Клиент','INT',0,NULL,'GetClientCodeWithNewUsers','1');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'CalculateByCatalog','Продукты без учета свойств (все цвета\вкусы объединены)','BOOL',0,NULL,'','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'PriceCode','Прайс-лист','INT',0,NULL,'GetPriceCode','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'ReportIsFull','По всему ассортименту','BOOL',0,NULL,'','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'FirmCodeEqual','Список поставщиков','LIST',1,NULL,'GetAllFirmCode','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'IgnoredSuppliers','Игнорируемые поставщики','LIST',1,NULL,'GetFirmCode','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'SupplierNoise','Зашумлять все прайс листы всех поставщиков кроме','INT',1,NULL,'GetFirmCode','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'ByBaseCosts','По базовым ценам','BOOL',0,NULL,NULL,'0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'PriceCodeEqual','Список значений "Прайс"','LIST',1,NULL,'GetPricesByRegionMask','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'RegionEqual','Список значений "Региона"','LIST',0,NULL,'GetRegion','0');
INSERT INTO reports.report_type_properties (`ReportTypeCode`,`PropertyName`,`DisplayName`,`PropertyType`,`Optional`,`PropertyEnumID`,`SelectStoredProcedure`,`DefaultValue`) VALUES ((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'),'UserCode','Пользователь','ENUM','1',NULL,NULL,0);

INSERT INTO reports.report_type_properties (ReportTypeCode, PropertyName, DisplayName, PropertyType, Optional, DefaultValue) VALUES((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'), 'ByWeightCosts', 'По взвешенным ценам', 'BOOL', 0, 0);
INSERT INTO reports.report_type_properties (ReportTypeCode, PropertyName, DisplayName, PropertyType, Optional, DefaultValue) VALUES((select r.ReportTypeCode FROM reports.reporttypes r where ReportTypeFilePrefix='OffersReportAsc'), 'MaxCostCount', 'Количество отображаемых цен', 'INT', 0, 3);